Feature/deployment
PTSS-Support/Authentication-Service pull request #13
Opened 2024-12-28 09:27 UTC by Tayam-El-Jebari

added flows for deployment

2024-12-28 13:40 UTC, DaanTol approved these changes, later dismissed

2024-12-28 18:03 UTC, SemPlaatsman requested changes
Er staat nog oude code in en de deploy to prod workflow is incorrect. Kijk goed naar de code in de base repo

2024-12-28 18:03 UTC, SemPlaatsman commented on .github/workflows/deploy-prod.yml
Deploy to production moet altijd op basis van de image die gemaakt is in de deploy prod workflow. Kijk naar de deploy-dev workflow in de base repo.

2024-12-28 18:03 UTC, SemPlaatsman commented on helm/templates/configmaps.yaml
Kan weg, is oude code

2024-12-28 18:03 UTC, SemPlaatsman commented on helm/templates/deployment.yaml
Opnieuw, oude code. Check de base repo

2024-12-29 14:23 UTC, SemPlaatsman approved these changes, later dismissed
Volledig functioneel, alleen twee kleine schoonheidsfoutjes, verder heel mooi 👍

2024-12-29 14:23 UTC, SemPlaatsman commented on .github/workflows/deploy-prod.yml
> +        required: true
Image tag is required maar nu staat er "(optional)".

2024-12-29 14:23 UTC, SemPlaatsman commented on .github/workflows/deploy-prod.yml
> +      - name: Deploy to OpenShift Pro
Klein ding:

+d

Pro => Prod

2025-01-02 13:12 UTC, Tayam-El-Jebari commented
> Volledig functioneel, alleen twee kleine schoonheidsfoutjes, verder heel mooi 👍

beidde goed gespot, tx

2025-01-02 13:43 UTC, SemPlaatsman approved these changes, later dismissed

2025-01-02 14:19 UTC, SemPlaatsman approved these changes, later dismissed

2025-01-02 14:19 UTC, SemPlaatsman approved these changes, later dismissed

2025-01-02 15:21 UTC, DaanTol submitted a review, later dismissed

2025-01-02 15:22 UTC, DaanTol approved these changes, later dismissed

2025-01-02 17:20 UTC, merged